In [70]:
import pandas as pd
from datetime import datetime
import numpy as np
import scipy
import seaborn as sns
import matplotlib.pyplot as plt

In [77]:
Amiata = pd.read_csv("Water_Spring_Amiata.csv")
Lupa = pd.read_csv("Water_Spring_Lupa.csv")
Madonna = pd.read_csv("Water_Spring_Madonna_di_Canneto.csv")

In [78]:
Amiata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7487 entries, 0 to 7486
Data columns (total 16 columns):
 #   Column                                 Non-Null Count  Dtype  
---  ------                                 --------------  -----  
 0   Date                                   7487 non-null   object 
 1   Rainfall_Castel_del_Piano              6291 non-null   float64
 2   Rainfall_Abbadia_S_Salvatore           3586 non-null   float64
 3   Rainfall_S_Fiora                       2633 non-null   float64
 4   Rainfall_Laghetto_Verde                2865 non-null   float64
 5   Rainfall_Vetta_Amiata                  2212 non-null   float64
 6   Depth_to_Groundwater_S_Fiora_8         3569 non-null   float64
 7   Depth_to_Groundwater_S_Fiora_11bis     3594 non-null   float64
 8   Depth_to_Groundwater_David_Lazzaretti  3242 non-null   float64
 9   Temperature_Abbadia_S_Salvatore        3583 non-null   float64
 10  Temperature_S_Fiora                    7487 non-null   float64
 11  Temp

In [79]:
Lupa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4199 entries, 0 to 4198
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Date            4199 non-null   object 
 1   Rainfall_Terni  4199 non-null   float64
 2   Flow_Rate_Lupa  3817 non-null   float64
dtypes: float64(2), object(1)
memory usage: 98.5+ KB


In [80]:
Madonna.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3113 entries, 0 to 3112
Data columns (total 4 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Date                          3104 non-null   object 
 1   Rainfall_Settefrati           2557 non-null   float64
 2   Temperature_Settefrati        2557 non-null   float64
 3   Flow_Rate_Madonna_di_Canneto  1387 non-null   float64
dtypes: float64(3), object(1)
memory usage: 97.4+ KB


In [81]:
Madonna['date'] = pd.to_datetime(Madonna['Date'], format='%d/%m/%Y')
Madonna = Madonna[Madonna['date'].notna()]

In [82]:
Madonna['date'] = Madonna['Date'].apply(lambda x: datetime.strptime(x, "%d/%m/%Y"))
y = Madonna.iloc[0]['date'].year
Madonna['year-month'] = Madonna['date'].apply(lambda x: int((x.year-y)*12+x.month))
Madonna['month/day'] = Madonna['date'].apply(lambda x:str(x.month) + "/" + str(x.day))
Madonna['year'] = Madonna['date'].apply(lambda x: int(x.year))
Madonna['month'] = Madonna['date'].apply(lambda x: int(x.month))
Madonna['day'] = Madonna['date'].apply(lambda x: int(x.day))

In [83]:
Madonna.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3104 entries, 0 to 3103
Data columns (total 10 columns):
 #   Column                        Non-Null Count  Dtype         
---  ------                        --------------  -----         
 0   Date                          3104 non-null   object        
 1   Rainfall_Settefrati           2557 non-null   float64       
 2   Temperature_Settefrati        2557 non-null   float64       
 3   Flow_Rate_Madonna_di_Canneto  1387 non-null   float64       
 4   date                          3104 non-null   datetime64[ns]
 5   year-month                    3104 non-null   int64         
 6   month/day                     3104 non-null   object        
 7   year                          3104 non-null   int64         
 8   month                         3104 non-null   int64         
 9   day                           3104 non-null   int64         
dtypes: datetime64[ns](1), float64(3), int64(4), object(2)
memory usage: 266.8+ KB


In [84]:
col = list(Madonna)
col

['Date',
 'Rainfall_Settefrati',
 'Temperature_Settefrati',
 'Flow_Rate_Madonna_di_Canneto',
 'date',
 'year-month',
 'month/day',
 'year',
 'month',
 'day']

In [85]:
Madonna = Madonna[['Date',
 'date',
 'year-month',
 'month/day',
 'year',
 'month',
 'day','Temperature_Settefrati','Rainfall_Settefrati',
 'Flow_Rate_Madonna_di_Canneto']]

In [86]:
Madonna.head()

Date       date  year-month month/day  year  month  day  \
0  01/01/2012 2012-01-01           1       1/1  2012      1    1   
1  02/01/2012 2012-01-02           1       1/2  2012      1    2   
2  03/01/2012 2012-01-03           1       1/3  2012      1    3   
3  04/01/2012 2012-01-04           1       1/4  2012      1    4   
4  05/01/2012 2012-01-05           1       1/5  2012      1    5   

   Temperature_Settefrati  Rainfall_Settefrati  Flow_Rate_Madonna_di_Canneto  
0                    5.25                  0.0                           NaN  
1                    6.65                  5.6                           NaN  
2                    8.85                 10.0                           NaN  
3                    6.75                  0.0                           NaN  
4                    5.55                  1.0                           NaN

In [87]:
sum_Madonna = Madonna.groupby(['month','day'],as_index=False).agg({'Flow_Rate_Madonna_di_Canneto':'mean'})
sum_Madonna

month  day  Flow_Rate_Madonna_di_Canneto
0        1    1                    268.391583
1        1    2                    268.142444
2        1    3                    268.434722
3        1    4                    270.829817
4        1    5                    270.665594
..     ...  ...                           ...
361     12   27                    269.188484
362     12   28                    268.900726
363     12   29                    269.001473
364     12   30                    269.136241
365     12   31                    268.764277

[366 rows x 3 columns]

In [88]:
#sum_Lupa.to_csv('sum_Lupa.csv',index=False)
#Lupa.to_csv('Lupa.csv',index=False)

In [89]:
numbers = sum_Madonna['Flow_Rate_Madonna_di_Canneto']
window_size = 5

i = 0
moving_averages = []
while i < len(numbers) - window_size + 1:
    this_window = numbers[i : i + window_size]
    
    window_average = sum(this_window) / window_size
    moving_averages.append(window_average)
    i += 1

In [90]:
moving_averages.append(-95.481818)
moving_averages.append(-95.493636)
moving_averages.append(-95.503636)
moving_averages.append(-95.513636)

In [91]:
len(moving_averages)

366

In [92]:
sum_Madonna['MA'] = moving_averages

In [93]:
Madonna[Madonna['Flow_Rate_Madonna_di_Canneto'].isnull().values==True]

Date       date  year-month month/day  year  month  day  \
0     01/01/2012 2012-01-01           1       1/1  2012      1    1   
1     02/01/2012 2012-01-02           1       1/2  2012      1    2   
2     03/01/2012 2012-01-03           1       1/3  2012      1    3   
3     04/01/2012 2012-01-04           1       1/4  2012      1    4   
4     05/01/2012 2012-01-05           1       1/5  2012      1    5   
...          ...        ...         ...       ...   ...    ...  ...   
2934  13/01/2020 2020-01-13          97      1/13  2020      1   13   
2935  14/01/2020 2020-01-14          97      1/14  2020      1   14   
2939  18/01/2020 2020-01-18          97      1/18  2020      1   18   
2940  19/01/2020 2020-01-19          97      1/19  2020      1   19   
2941  20/01/2020 2020-01-20          97      1/20  2020      1   20   

      Temperature_Settefrati  Rainfall_Settefrati  \
0                       5.25                  0.0   
1                       6.65                  5.6   
2                       8.85                 10.0   
3                       6.75                  0.0   
4                       5.55                  1.0   
...                      ...                  ...   
2934                     NaN                  NaN   
2935                     NaN                  NaN   
2939                     NaN                  NaN   
2940                     NaN                  NaN   
2941                     NaN                  NaN   

      Flow_Rate_Madonna_di_Canneto  
0                              NaN  
1                              NaN  
2                              NaN  
3                              NaN  
4                              NaN  
...                            ...  
2934                           NaN  
2935                           NaN  
2939                           NaN  
2940                           NaN  
2941                           NaN  

[1717 rows x 10 columns]

In [94]:
#newLupa=pd.read_csv('lupa.csv')

In [95]:
#newLupa.info()

In [96]:
mergedData= pd.merge(Madonna,sum_Madonna, how='left' ,left_on=['month','day'], right_on=['month','day'])
mergedData

Date       date  year-month month/day  year  month  day  \
0     01/01/2012 2012-01-01           1       1/1  2012      1    1   
1     02/01/2012 2012-01-02           1       1/2  2012      1    2   
2     03/01/2012 2012-01-03           1       1/3  2012      1    3   
3     04/01/2012 2012-01-04           1       1/4  2012      1    4   
4     05/01/2012 2012-01-05           1       1/5  2012      1    5   
...          ...        ...         ...       ...   ...    ...  ...   
3099  26/06/2020 2020-06-26         102      6/26  2020      6   26   
3100  27/06/2020 2020-06-27         102      6/27  2020      6   27   
3101  28/06/2020 2020-06-28         102      6/28  2020      6   28   
3102  29/06/2020 2020-06-29         102      6/29  2020      6   29   
3103  30/06/2020 2020-06-30         102      6/30  2020      6   30   

      Temperature_Settefrati  Rainfall_Settefrati  \
0                       5.25                  0.0   
1                       6.65                  5.6   
2                       8.85                 10.0   
3                       6.75                  0.0   
4                       5.55                  1.0   
...                      ...                  ...   
3099                     NaN                  NaN   
3100                     NaN                  NaN   
3101                     NaN                  NaN   
3102                     NaN                  NaN   
3103                     NaN                  NaN   

      Flow_Rate_Madonna_di_Canneto_x  Flow_Rate_Madonna_di_Canneto_y  \
0                                NaN                      268.391583   
1                                NaN                      268.142444   
2                                NaN                      268.434722   
3                                NaN                      270.829817   
4                                NaN                      270.665594   
...                              ...                             ...   
3099                      223.919115                      252.898212   
3100                      223.861787                      253.009336   
3101                      223.764382                      252.702677   
3102                      223.766272                      252.983781   
3103                      223.752653                      252.609161   

              MA  
0     269.292832  
1     269.137500  
2     269.545936  
3     269.898973  
4     269.773617  
...          ...  
3099  252.840633  
3100  254.798631  
3101  259.590196  
3102  266.033438  
3103  272.389606  

[3104 rows x 12 columns]

In [97]:
mergedData.Flow_Rate_Madonna_di_Canneto_x.fillna(mergedData.Flow_Rate_Madonna_di_Canneto_y, inplace=True)
mergedData = mergedData.drop(columns=['Flow_Rate_Madonna_di_Canneto_y','MA'])

In [98]:
mergedData.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3104 entries, 0 to 3103
Data columns (total 10 columns):
 #   Column                          Non-Null Count  Dtype         
---  ------                          --------------  -----         
 0   Date                            3104 non-null   object        
 1   date                            3104 non-null   datetime64[ns]
 2   year-month                      3104 non-null   int64         
 3   month/day                       3104 non-null   object        
 4   year                            3104 non-null   int64         
 5   month                           3104 non-null   int64         
 6   day                             3104 non-null   int64         
 7   Temperature_Settefrati          2557 non-null   float64       
 8   Rainfall_Settefrati             2557 non-null   float64       
 9   Flow_Rate_Madonna_di_Canneto_x  3104 non-null   float64       
dtypes: datetime64[ns](1), float64(3), int64(4), object(2)
memory usage: 266.

In [99]:
test_data_size = 620
train_data = mergedData['Flow_Rate_Madonna_di_Canneto_x'][:-620]
test_data = mergedData['Flow_Rate_Madonna_di_Canneto_x'][-620:]


In [100]:
print(len(train_data))
print(len(test_data))

2484
620


In [101]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(-1, 1))
train_data_normalized = scaler.fit_transform(train_data.values.reshape(-1, 1))

In [102]:
print(train_data_normalized[:5])
print(train_data_normalized[-5:])

[[0.43474742]
 [0.43031464]
 [0.43551496]
 [0.47812935]
 [0.47520745]]
[[0.81513128]
 [0.82192326]
 [0.82356197]
 [0.82096104]
 [0.81909916]]


In [103]:
import torch
import torch.nn as nn

train_data_normalized = torch.FloatTensor(train_data_normalized).view(-1)

In [104]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")


In [105]:
train_window = 3

In [106]:
def create_inout_sequences(input_data, tw):
    inout_seq = []
    L = len(input_data)
    for i in range(L-tw):
        train_seq = input_data[i:i+tw]
        train_label = input_data[i+tw:i+tw+1]
        inout_seq.append((train_seq ,train_label))
    return inout_seq

In [107]:
train_inout_seq = create_inout_sequences(train_data_normalized, train_window)

In [108]:
train_inout_seq[:5]

[(tensor([0.4347, 0.4303, 0.4355]), tensor([0.4781])),
 (tensor([0.4303, 0.4355, 0.4781]), tensor([0.4752])),
 (tensor([0.4355, 0.4781, 0.4752]), tensor([0.4209])),
 (tensor([0.4781, 0.4752, 0.4209]), tensor([0.4666])),
 (tensor([0.4752, 0.4209, 0.4666]), tensor([0.4669]))]

In [109]:
class LSTM(nn.Module):
    def __init__(self, input_size=1, hidden_layer_size=100, output_size=1):
        super().__init__()
        self.hidden_layer_size = hidden_layer_size

        self.lstm = nn.LSTM(input_size, hidden_layer_size).to(device)

        self.linear = nn.Linear(hidden_layer_size, output_size).to(device)

        self.hidden_cell = (torch.zeros(1,1,self.hidden_layer_size).to(device),
                            torch.zeros(1,1,self.hidden_layer_size).to(device))

    def forward(self, input_seq):
        lstm_out, self.hidden_cell = self.lstm(input_seq.view(len(input_seq) ,1, -1), self.hidden_cell)
        predictions = self.linear(lstm_out.view(len(input_seq), -1))
        return predictions[-1]

In [110]:
model = LSTM().to(device)
loss_function = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [111]:
print(model)

LSTM(
  (lstm): LSTM(1, 100)
  (linear): Linear(in_features=100, out_features=1, bias=True)
)


In [112]:
epochs = 150

for i in range(epochs):
    for seq, labels in train_inout_seq:
        optimizer.zero_grad()
        model.hidden_cell = (torch.zeros(1, 1, model.hidden_layer_size).to(device),
                        torch.zeros(1, 1, model.hidden_layer_size).to(device))

        y_pred = model(seq.to(device))

        single_loss = loss_function(y_pred, labels.to(device))
        single_loss.backward()
        optimizer.step()

    if i%25 == 1:
        print(f'epoch: {i:3} loss: {single_loss.item():10.8f}')

print(f'epoch: {i:3} loss: {single_loss.item():10.10f}')

epoch:   1 loss: 0.00000037
epoch:  26 loss: 0.00001387
epoch:  51 loss: 0.00000780
epoch:  76 loss: 0.00000390
epoch: 101 loss: 0.00000593
epoch: 126 loss: 0.00000903
epoch: 149 loss: 0.0000111588


In [113]:
torch.cuda.get_device_name(0)

'GeForce RTX 2070 with Max-Q Design'

In [114]:
fut_pred = 620

test_inputs = train_data_normalized[-train_window:].tolist()
print(test_inputs)

[0.82356196641922, 0.820961058139801, 0.8190991878509521]


In [115]:
model.eval()

for i in range(fut_pred):
    seq = torch.FloatTensor(test_inputs[-train_window:]).to(device)
    with torch.no_grad():
        model.hidden = (torch.zeros(1, 1, model.hidden_layer_size).to(device),
                        torch.zeros(1, 1, model.hidden_layer_size).to(device))
        test_inputs.append(model(seq).item())

In [116]:
test_inputs[fut_pred:]

[1.1876462697982788, 1.1876462697982788, 1.1876462697982788]

In [117]:
actual_predictions = scaler.inverse_transform(np.array(test_inputs[train_window:] ).reshape(-1, 1))
print(actual_predictions)

[[293.27297972]
 [297.10617573]
 [300.38818732]
 [302.95872638]
 [304.92617592]
 [306.42485137]
 [307.56221445]
 [308.42036731]
 [309.06332871]
 [309.54135554]
 [309.89368316]
 [310.15076989]
 [310.33617974]
 [310.46806307]
 [310.56033585]
 [310.6236042 ]
 [310.66590817]
 [310.69325098]
 [310.71010155]
 [310.71975629]
 [310.72458031]
 [310.72628212]
 [310.72603421]
 [310.72468081]
 [310.7227646 ]
 [310.72064739]
 [310.71855028]
 [310.71660058]
 [310.71486527]
 [310.71336446]
 [310.71211156]
 [310.71107975]
 [310.71024225]
 [310.70956555]
 [310.70902955]
 [310.70862084]
 [310.70830594]
 [310.70806474]
 [310.70789054]
 [310.70776324]
 [310.70766944]
 [310.70759574]
 [310.70754214]
 [310.70750194]
 [310.70748184]
 [310.70746844]
 [310.70745504]
 [310.70745504]
 [310.70744834]
 [310.70744164]
 [310.70744164]
 [310.70744164]
 [310.70743494]
 [310.70742824]
 [310.70743494]
 [310.70743494]
 [310.70743494]
 [310.70743494]
 [310.70743494]
 [310.70743494]
 [310.70743494]
 [310.70743494]
 [310.70

In [118]:
from sklearn.metrics import mean_squared_error

mean_squared_error(test_data, actual_predictions,squared=False)

73.48799715758359